// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MaiF-_FmdzAum_-XQb7-Dd4ytAwSWCI',
    appId: '1:309112104218:android:77d7de820dc1ce3d65f8a3',
    messagingSenderId: '309112104218',
    projectId: 'pc-api-7942935858695830085-634',
    storageBucket: 'pc-api-7942935858695830085-634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ63WT7wR6dHA4NxqSHJeT-0ENPWn31WY',
    appId: '1:309112104218:ios:a2e8d728e3ac367465f8a3',
    messagingSenderId: '309112104218',
    projectId: 'pc-api-7942935858695830085-634',
    storageBucket: 'pc-api-7942935858695830085-634.appspot.com',
    iosClientId: '309112104218-vnbe07d0rfvr90k7ek0btu7kjs024q1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManager',
  );
}
